{% set name = "jupyterhub-yarnspawner" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 138d9ab2de6a451ed2909f61f8f8fd3f63784e3d9ab7787014de396f605c4c19

build:
  number: 1000
  skip: True  # [win or osx or py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jupyterhub >=0.8.0
    - skein >=0.5.0

test:
  imports:
    - yarnspawner

about:
  home: https://github.com/jcrist/yarnspawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Spawn JupyterHub servers in Apache Hadoop/YARN containers
  description: |
    A JupyterHub Spawner for launching notebook servers inside Apache
    Hadoop/YARN containers.
  doc_url: https://jcrist.github.io/yarnspawner/
  dev_url: https://github.com/jcrist/yarnspawner

extra:
  recipe-maintainers:
    - jcrist
